### ISSUE TITLE
如何用 Shiviz 工具可视化 log 日志

### ISSUE THREAD

**Issue by chauncey-77** [FudanSELab/research#1]
![image](https://user-images.githubusercontent.com/20733933/63573814-ed747f00-c5b8-11e9-8b34-0b40599c08dd.png)
你好，在这个文件中你们给出了类似于一个json格式的文本，这应该是一个log日志，请问我要怎么将这个log日志利用 Shiviz 工具可视化呢？直接在 Shiviz 网站上导入这个文件貌似是不行的，也没有相应的正则表达式。我看到你们好像有一个 Json2Shiviz 文件夹，你能详细地讲讲要怎么操作吗？谢谢！

**Comment by Blanchedingding** [comment]
Please try following expressions in ShiViz after selecting the  _all.txt_ file.

Log parsing regular expression:
`{traceId\=(?<traceId>[^\,]*)\, spanId\=(?<spanId>[^\,]*)\, hostName\=(?<hostName>[^\,]*)\,( srcName\=(?<srcName>[^\,]*)\,)?( destName\=(?<destName>[^\,]*)\,)?( src\=(?<src>[^\,]*)\,)? host\=(?<host>[^\,]*)\,( api\=(?<API>[^\,]*)\,)? clock\=(?<clock>{.*})\,( dest\=(?<dest>[^\,]*)\,)? event\=(?<event>[^\,]*)\, type\=(?<type>[^\,]*)\,( error\=(?<error>[^\,]*)\,)? parentId\=(?<parentId>[^\,]*)\, timestamp=(?<timestamp>\d*)\, }`

Multiple executions regular expression delimiter:
`^=== (?<trace>.*) ===$`

**Comment by chauncey-77** [comment]
谢谢！
